version: "3"

services:

  ### geth ################################################
  geth:
    image: ethereum/client-go
    # restart: always
    container_name: geth
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - ./geth-data:/root
    command:
      - "--cache"
      - "1024"
      - "--syncmode"
      - "fast"
      - --networkid
      - "1"
      - "--maxpeers"
      - "24"
      - "--http"
      - "--http.port"
      - "8545"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.api"
      - "txpool,eth,web3,admin,personal,net"

  ### bitcoind ################################################
  bitcoind:
    image: amacneil/bitcoin
    container_name: bitcoind
    # restart: always
    # specify additional command line arguments here
    command: bitcoind
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      # change to 18333 if running testnet
      - "8333:8333"
    volumes:
      - ./bitcoin-data:/data
  bitcoin-cli:
    image: amacneil/bitcoin
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: ""
    depends_on:
      - bitcoind
    network_mode: service:bitcoind


